---
group: sota-core
pipelines:
  - name: build
    env: build
    materials:
      - type: git
        repo: https://github.com/alaa/pencil.git
        branch: master
    stages:
      - name: build
        manual: false
        fetch_artifact: false
        jobs:
          - name: generate_artifact
            tasks:
              - type: exec
                fetch_artifact: false
                command: echo alaa > artifact.txt
  - name: ci.deploy
    env: build
    materials:
      - type: git
        repo: https://github.com/alaa/pencil.git
        branch: master
      - type: dependency
        upstream_pipeline: sota-core.build
        upstream_stage: build
    stages:
      - name: marathon
        manual: false
        fetch_artifact: true
        jobs:
          - name: deploy
            tasks:
              - type: fetch_artifact
                upstream_pipeline: sota-core.build
                upstream_stage: build
                upstream_job: generate_artifact
              - type: exec
                fetch_artifact: false
                command: echo 'deploying to staging...'
  - name: ci.approve
    env: build
    materials:
      - type: dependency
        upstream_pipeline: sota-core.ci.deploy
        upstream_stage: marathon
    stages:
      - name: approve
        manual: true
        fetch_artifact: true
        jobs:
          - name: approve
            tasks:
              - type: fetch_artifact
                upstream_pipeline: sota-core.ci.deploy
                upstream_stage: marathon
                upstream_job: deploy
              - type: exec
                fetch_artifact: false
                command: echo 'approving staging build to qa ...'
  - name: qa.deploy
    env: build
    materials:
      - type: git
        repo: https://github.com/alaa/pencil.git
        branch: master
      - type: dependency
        upstream_pipeline: sota-core.ci.approve
        upstream_stage: approve
    stages:
      - name: marathon
        manual: false
        fetch_artifact: true
        jobs:
          - name: deploy
            tasks:
              - type: fetch_artifact
                upstream_pipeline: sota-core.ci.approve
                upstream_stage: approve
                upstream_job: approve
              - type: exec
                fetch_artifact: false
                command: echo 'deploying to QA...'
