---
group: sota30
pipelines:
  - name: build
    env: loadtest
    materials:
      - type: git
        repo: https://github.com/advancedtelematic/rvi_sota_server.git
        branch: demo
    stages:
      - name: sbt-release
        manual: false
        jobs:
          - name: sbt-release
            tasks:
              - type: exec
                command: sbt sota-device_registry/docker:publish && tag=$(git describe); echo ${tag:1}-SNAPSHOT > artifact.txt
  - name: ci.deploy
    env: loadtest
    materials:
      - type: git
        repo: git@github.com:advancedtelematic/sota-deploy.git
        branch: master
      - type: dependency
        upstream_pipeline: $group.build
        upstream_stage: sbt-release
    stages:
      - name: marathon
        manual: false
        jobs:
          - name: deploy
            tasks:
              - type: fetch_artifact
                upstream_pipeline: $group.build
                upstream_stage: sbt-release
                upstream_job: sbt-release
              - type: exec
                command: ./deploy-env/deploy.sh ci device-registry advancedtelematic/sota-device_registry:$(cat artifact.txt)
  - name: ci.approve
    env: loadtest
    materials:
      - type: dependency
        upstream_pipeline: $group.ci.deploy
        upstream_stage: marathon
    stages:
      - name: approve
        manual: true
        jobs:
          - name: approve
            tasks:
              - type: fetch_artifact
                upstream_pipeline: $group.ci.deploy
                upstream_stage: marathon
                upstream_job: deploy
              - type: exec
                command: echo 'approving staging build to qa ...' && cat artifact.txt
  - name: qa.deploy
    env: loadtest
    materials:
      - type: git
        repo: git@github.com:advancedtelematic/sota-deploy.git
        branch: master
      - type: dependency
        upstream_pipeline: $group.ci.approve
        upstream_stage: approve
    stages:
      - name: marathon
        manual: false
        jobs:
          - name: deploy
            tasks:
              - type: fetch_artifact
                upstream_pipeline: $group.ci.approve
                upstream_stage: approve
                upstream_job: approve
              - type: exec
                command: ./deploy-env/deploy.sh qa device-registry advancedtelematic/sota-device_registry:$(cat artifact.txt)
  - name: qa.approve
    env: loadtest
    materials:
      - type: dependency
        upstream_pipeline: $group.qa.deploy
        upstream_stage: marathon
    stages:
      - name: approve
        manual: true
        jobs:
          - name: approve
            tasks:
              - type: fetch_artifact
                upstream_pipeline: $group.qa.deploy
                upstream_stage: marathon
                upstream_job: deploy
              - type: exec
                command: echo 'approving QA build to production ...' && cat artifact.txt
